fixtures:
  repositories:
    'easy_type':
      repo: 'git://github.com/hajee/easy_type.git'
    'yamlfile':
      repo: 'git://github.com/reidmv/puppet-module-yamlfile'
    'filemapper':
      repo: 'git://github.com/adrienthebo/puppet-filemapper'
    'sleep':
      repo: 'git://github.com/fiddyspence/puppet-sleep'
  symlinks:
    'orawls': '#{source_dir}'