fixtures:
  forge_modules:
    easy_type: "hajee/easy_type"
  repositories:
    'yamlfile':
      repo: 'git://github.com/reidmv/puppet-module-yamlfile'
    'filemapper':
      repo: 'git://github.com/adrienthebo/puppet-filemapper'
    'sleep':
      repo: 'git://github.com/fiddyspence/puppet-sleep'
  symlinks:
    'orawls': '#{source_dir}'