name 'fiddyspence-sleep'
version '1.1.2'
source 'git://github.com/fiddyspence/puppet-sleep.git'
description 'This is a module to provide a core type that does a sleep'
author 'fiddyspence'
license 'ASL 2.0'
summary 'Sleep Module'
project_page 'http://github.com/fiddyspence/puppet-sleep'
