# inherit_from: rubocop-todo.yml

AllCops:
  Exclude:
    - 'spec/**'
    - 'lib/1.8.7/**'

Eval:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false

LineLength:
  Max: 132

AccessorMethodName:
  Enabled: false

MethodLength:
  Max: 20
